name: Build and Autotest

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
        with:
          gradle-version: '8.9'

      # NOTE: The Gradle Wrapper is the default and recommended way to run Gradle (https://docs.gradle.org/current/userguide/gradle_wrapper.html).
      # If your project does not have the Gradle Wrapper configured, you can use the following configuration to run Gradle with a specified version.
      #
      # - name: Setup Gradle
      #   uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      #   with:
      #     gradle-version: '8.9'
      #
      - name: Build JARs
        run: gradle jar

      - name: Save Client JAR
        uses: actions/upload-artifact@v4.3.1
        with:
          name: AES-Hashing-Client-5785.jar
          path: AES-Hashing-Client/build/libs/
          retention-days: 30
          overwrite: true

      - name: Save Server JAR
        uses: actions/upload-artifact@v4.3.1
        with:
          name: AES-Hashing-Server-5785.jar
          path: AES-Hashing-Server/build/libs/
          retention-days: 30
          overwrite: true

      - name: Run the tests
        run: |
          cp AES-Hashing-Client/build/libs/AES-Hashing-Client-5785.jar .
          cp AES-Hashing-Server/build/libs/AES-Hashing-Server-5785.jar .        
          chmod 700 automated-hashing-test-script.sh
          ./automated-hashing-test-script.sh

      - name: Save text ouptut files
        uses: actions/upload-artifact@v4.3.1
        with:
          name: text-outputs
          path: ./Test*.txt
          retention-days: 30

      - name: Save decrypted sha256digests
        uses: actions/upload-artifact@v4.3.1
        with:
          name: digest files
          path: decryptedfiles/decryptedfiles.sha256
          retention-days: 30

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
      # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
        with:
          gradle-version: '8.9'